monolog:
    channels:
        ['metric', 'tgbot', 'slack', 'email']
    handlers:
        email:
            type: stream
            path: "%kernel.logs_dir%/send_email.log"
            level: info
            channels: ["email"]
        tgbot:
            type: stream
            path: "%kernel.logs_dir%/tg_bot.log"
            level: info
            channels: ["tgbot"]
        metrics:
            type: stream
            path: "%kernel.logs_dir%/metric.log"
            level: info
            channels: ["metric"]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!metric"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console", "!metric"]