easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Call
        - App\Entity\Answer
        - App\Entity\Question
        - App\Entity\CallStep
        - App\Entity\User
        - App\Entity\Community
        - App\Entity\UserAdmin
