monolog:
    channels:
        ['metric', 'tgbot', 'slack', 'email']
    handlers:
        email:
            type: stream
            path: "%kernel.logs_dir%/send_email.log"
            level: info
            channels: ["email"]
        tgbot:
            type: stream
            path: "%kernel.logs_dir%/tg_bot.log"
            level: info
            channels: ["tgbot"]
        metrics:
            type: stream
            path: "%kernel.logs_dir%/metric.log"
            level: info
            channels: ["metric"]
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        main_critical:
            type: fingers_crossed
            action_level: critical
            handler: nested_critical
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        nested_critical:
            type: stream
            path: "%kernel.logs_dir%/critical_%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        # Slack ————————————————————————————————————————————————————————————————

        # Critical errors only
        slack_errors:
            type:        slack
            token:       '%env(SLACK_TOKEN)%'
            channel:     '%env(SLACK_CHANNEL)%'
            icon_emoji:  ':ghost:' # 👻
            level:         critical
            include_extra: true

        # Application's messages
        slack:
            type:        slack
            token:       '%env(SLACK_TOKEN)%'
            channel:     '%env(SLACK_CHANNEL)%'
            icon_emoji:  ":heavy_check_mark:" # ✅
            level:       debug
            include_extra: true
            channels:    ['slack']
